### ISSUE TITLE
Tests - Service, Facade: Hero

### ISSUE THREAD

**Issue by GreenManSK** [GreenManSK/PA165-D-D-Troops#19]

**Comment by makovako** [comment]
Tests to implement:
# ServiceTest
- get by id, get by id non existent
- get all, get all empty
- create, create null, create invalid
- update, update null, update invalid
- delete, delete non existent
## Search - parameters role, race, fromExperience, toExperience
- every parameter null
- one, two, three parameters null (All combinations) ???
- fromExperience greater than toExperience
- non existent/valid Role ???
- role not assigned to any hero


# FacadeTest
- get by id
- get all
- create, update, delete
## Search
- searchHeroDto valid
- searchHeroDto null
- some/all parameters null ??? (as in service part)

**Comment by GreenManSK** [comment]
Service search
- It would be really cool if you manage to test all combinations of null, but I can understand if that would be too much, so test for every parameter filled, all null and one only one parameter not null should be enough. Maybe one test case when only fromExp and toExp is not null
- fromExperience greater than toExperience, also don't forget to test border values and from=to
- non existent/valid Role ??? - that's not needed
- role not assigned to any hero - that's not needed

We need only one test on each method of facade, so searchHeroDto valid should be enought.
